const data = [
  {
    id: 1,
    url: 'images/img1.jpg',
    title: 'Bible',
    isfavorite: false,
    price: 1.8,
    qty: 1,
    total: 0,
  },
  {
    id: 2,
    url: 'images/img2.jpg',
    title: 'flip book',
    price: 1.5,
    qty: 1,
    total: 0,
  },
  {
    id: 3,
    url: 'images/img3.jpg',
    title: 'book on the shelf',
    isfavorite: false,
    price: 1.2,
    qty: 1,
    total: 0,
  },
  {
    id: 4,
    url: 'images/img4.jpg',
    title: 'leisure time',
    isfavorite: false,
    price: 1.3,
    qty: 1,
    total: 0,
  },
  {
    id: 5,
    url: 'images/img5.jpg',
    title: 'time with angels',
    isfavorite: false,
    price: 1.2,
    qty: 1,
    total: 0,
  },
  {
    id: 6,
    url: 'images/img6.jpg',
    title: 'quiet time',
    isfavorite: false,
    price: 2.5,
    qty: 1,
    total: 0,
  },
  {
    id: 7,
    url: 'images/img7.jpg',
    title: 'heap of books',
    isfavorite: false,
    price: 1.2,
    qty: 1,
    total: 0,
  },
  {
    id: 8,
    url: 'images/img8.jpg',
    title: 'Library',
    isfavorite: false,
    price: 1.9,
    qty: 1,
    total: 0,
  },
]

export default data
